### DISCUSSION TITLE
v1.5.8-alpha - 网页版 - Markdown 支持

### DISCUSSION THREAD

**Discussion by lss233** [lss233/chatgpt-mirai-qq-bot#195] [General]
这是一个针对网页版的**测试更新**，可能会诸多问题，仅有需要体验的人士使用，欢迎反馈 BUG。项目文档：[README](https://github.com/lss233/chatgpt-mirai-qq-bot/tree/browser-version)

Linux 用户：你可以使用下面这个命令实现此系列的一键部署。  
```
bash -c "$(curl -fsSL https://gist.githubusercontent.com/lss233/54f0f794f2157665768b1bdcbed837fd/raw/chatgpt-mirai-installer-154-16RC3.sh)"
```
## 更新内容
* 新增：Markdown、TeX 公式渲染支持 by @Hakureirm, @acai66, @lss233 in https://github.com/lss233/chatgpt-mirai-qq-bot/pull/188
* 新增：Windows 快速部署包现在会将所有需要的文件统一打包，用户初始化时不再需要额外下载依赖 https://github.com/lss233/chatgpt-mirai-qq-bot/pull/193
* 修复：删除自带的默认预设 

## 升级方法
* Windows 快速部署包用户：备份 `chatgpt\config.cfg`，下载最新的快速部署包，然后将部署包中的 chatgpt 文件夹**覆盖**至旧的文件夹，再还原备份。
* Linux 一键脚本部署用户：自动升级，无需操作
* docker 部署用户： 执行 `docker pull lss233/chatgpt-mirai-qq-bot:browser-version` 拉取最新镜像，重新创建容器
* docker-compose 部署用户： 修改 docker-compose.yml，执行 `docker-compose pull`，按照下文步骤创建新的配置文件后，再执行 `docker-compose up -d` 更新最新镜像
```yml

version: '3.4'
services:
  mirai:
    image: lss233/mirai-http:latest
    restart: always
    environment:
      LANG: 'C.UTF-8'
    volumes:
      - ./mirai/bots:/app/bots
      - ./mirai/config:/app/config
      - ./mirai/data:/app/data
      - ./mirai/plugin-libraries:/app/plugin-libraries
      - ./mirai/libs:/app/libs
      # - ./mirai/config.json:/app/config.json # 如果你要修改 mcl 的设置，就解除这个注释
  chatgpt:
    image: lss233/chatgpt-mirai-qq-bot:browser-version
    restart: always
    environment:
      LANG: 'C.UTF-8'
      XPRA_PASSWORD: 'lss233' # XPRA 密码，建议修改
    ports:
      - 14500:14500
    volumes:
      - ./config.cfg:/app/config.cfg
      # - ./fonts:/app/fonts # 如果你想自定义字体，就解除注释
      # - ./presets:/app/presets # 如果你想自定义预设，就解除注释
  watchtower: # [可选] 自动更新
    image: containrrr/watchtower
    volumes: # 如果启动失败，请修改下面这条：
      - /var/run/docker.sock:/var/run/docker.sock
```

**Full Changelog**: https://github.com/lss233/chatgpt-mirai-qq-bot/compare/v1.5.7...v1.5.8-alpha

<hr /><em>This discussion was created from the release <a href='https://github.com/lss233/chatgpt-mirai-qq-bot/releases/tag/v1.5.8-alpha'>v1.5.8-alpha - 网页版 - Markdown 支持</a>.</em>
