### DISCUSSION TITLE
v2.0 - 正式版 - 支持 Bing GPT、额度限制

### DISCUSSION THREAD

**Discussion by lss233** [lss233/chatgpt-mirai-qq-bot#249] [Announcements]
Linux 用户：你可以使用下面这个命令实现此系列的一键部署。  
```
bash -c "$(curl -fsSL https://gist.githubusercontent.com/lss233/54f0f794f2157665768b1bdcbed837fd/raw/chatgpt-mirai-installer-154-16RC3.sh)"
```
Windows 用户：你可以下载下方的 Windows 部署包来实现快速部署。  

## 更新内容
* 重构了大部分代码，提高维护性
* 新增：支持 Bing GPT
* 新增：通过命令来切换使用不同的 AI
* 新增：通过命令来切换文字和图片模式
* 新增：可以通过命令来重新载入配置文件
* 新增：限制指定用户/群组的使用频率
* 修复：改进了配置文件的中的描述
* 修复：API 版 ChatGPT 无法使用的问题

## 升级方法
* Windows 快速部署包用户：备份 `chatgpt\config.cfg`，下载最新的快速部署包，然后将部署包中的 chatgpt 文件夹**覆盖**至旧的文件夹，再还原备份。
* Linux 一键脚本部署用户：自动升级，无需操作
* docker 部署用户： 执行 `docker pull lss233/chatgpt-mirai-qq-bot:browser-version` 拉取最新镜像，重新创建容器
* docker-compose 部署用户： 修改 docker-compose.yml，执行 `docker-compose pull`，按照下文步骤创建新的配置文件后，再执行 `docker-compose up -d` 更新最新镜像
```yml

version: '3.4'
services:
  mirai:
    image: lss233/mirai-http:latest
    restart: always
    environment:
      LANG: 'C.UTF-8'
    volumes:
      - ./mirai/bots:/app/bots
      - ./mirai/config:/app/config
      - ./mirai/data:/app/data
      # - ./mirai/config.json:/app/config.json # 如果你要修改 mcl 的设置，就解除这个注释
  chatgpt:
    image: lss233/chatgpt-mirai-qq-bot:browser-version
    restart: always
    environment:
      LANG: 'C.UTF-8'
      XPRA_PASSWORD: 'lss233' # XPRA 密码，建议修改
    ports:
      - 14500:14500
    volumes:
      - ./config.cfg:/app/config.cfg
      # - ./fonts:/app/fonts # 如果你想自定义字体，就解除注释
      # - ./presets:/app/presets # 如果你想自定义预设，就解除注释
  watchtower: # [可选] 自动更新
    image: containrrr/watchtower
    volumes: # 如果启动失败，请修改下面这条：
      - /var/run/docker.sock:/var/run/docker.sock
```

**Full Changelog**: https://github.com/lss233/chatgpt-mirai-qq-bot/compare/v1.5.7...v1.5.8-alpha

<hr /><em>This discussion was created from the release <a href='https://github.com/lss233/chatgpt-mirai-qq-bot/releases/tag/v2.0'>v2.0 - 正式版 - 支持 Bing GPT、额度限制</a>.</em>
