### ISSUE TITLE
docker-compose 启动方式，报错ws连不上

### ISSUE THREAD

**Issue by systemctls** [lss233/chatgpt-mirai-qq-bot#125]
### docker
```
version: '3.4'
services:
  mirai:
    image: lss233/mirai-http:latest
    restart: always
    environment:
      LANG: 'C.UTF-8'
    volumes:
      - ./mirai/bots:/app/bots
      - ./mirai/config:/app/config
      - ./mirai/data:/app/data
      - ./mirai/plugin-libraries:/app/plugin-libraries
      - ./mirai/libs:/app/libs
      #- ./mirai/config.json:/mirai/config.json # 如果你要修改 mcl 的设置，就解除这个注释
  chatgpt:
    image: lss233/chatgpt-mirai-qq-bot:latest
    restart: always
    environment:
      LANG: 'C.UTF-8'
    volumes:
      - ./mirai/config/config.cfg:/app/config.cfg
      # - ./fonts:/app/fonts # 如果你想自定义字体，就解除注释
      # - ./presets:/app/presets # 如果你想自定义预设，就解除注释
```
### config
```
[mirai]
qq = 12812xxxxx

# 以下设置如果不了解，可以不用理会
api_key = "1234567890"
http_url = "http://localhost:8080"
ws_url = "http://localhost:8080"

[openai]

# 你的 OpenAI 邮箱
#email = "xxxx" 
# 你的 OpenAI 密码
#password = "xxx"

# 对于通过 Google 登录或者微软登录的同学，可以使用 session_token 登录
# 此时 email 和 password 可以直接删除
session_token = "ez9Q"

# 机器人情感值，范围  0 ~ 1，越高话越多
temperature = 0.5

# 如果你的网络不好，可以设置一个本地代理
# proxy="http://127.0.0.1:1080"

# 如果你 OpenAI 禁止你所在的地区使用，可以使用第三方服务代理验证
# 警告：设置为 true 以后，你的 OpenAI 账户信息会发送至第三方
insecure_auth = false

# 使用付费模型（plus 用户使用）
paid = false
[system]
# 是否自动同意进群邀请
accept_group_invite = false
# 是否自动同意好友请求
accept_friend_request = false

[presets]
# 切换预设的命令： 加载预设 猫娘
command = "加载预设 (\\w+)"
loaded_successful = "预设加载成功！"

[presets.keywords]
# 预设关键词 <-> 实际文件
"正常" = "presets/default.txt"
"猫娘" = "presets/catgirl.txt"
```
### 运行结果
![image](https://user-images.githubusercontent.com/37177191/218749054-0802cc18-35f5-498e-8029-a53327d917ca.png)
