### ISSUE TITLE
websocket 无法连接 Connection reset by peer

### ISSUE THREAD

**Issue by yhtprime** [lss233/chatgpt-mirai-qq-bot#164]
按照docker-compose教程安装了mirai
但是执行docker-compose up 之后出现了问题。我认为问题的出处是在mirai log的最后一行不知道什么原因input服务自动关闭了。。。
从log里找不到问题(error)所以提交issue。

**mirai log**
```
docker-compose up
[+] Running 1/1
 ⠿ Container mirai-mirai-1  Created                                                                                                                            0.4s
Attaching to mirai-mirai-1
mirai-mirai-1  |   05:11:01 [INFO] iTX Technologies Mirai Console Loader version 2.1.2-61c8bd8
mirai-mirai-1  |   05:11:01 [INFO] Runtime: OpenJDK 64-Bit Server VM 17.0.6 (arch: 64)
mirai-mirai-1  |   05:11:01 [INFO] https://github.com/iTXTech/mirai-console-loader
mirai-mirai-1  |   05:11:01 [INFO] This program is licensed under GNU AGPL v3
mirai-mirai-1  |   05:11:04 [INFO] Mirai Console Loader Announcement:
mirai-mirai-1  | Mirai Console Loader 公告栏
mirai-mirai-1  | 
mirai-mirai-1  | 如果在图片上传的时候遇到问题请与我们联系 (需要提供图片文件源本)
mirai-mirai-1  | `- 如 Unsupported image type for ExternalResource *
mirai-mirai-1  | `  considering use gif/png/bmp/jpg format.
mirai-mirai-1  | `- Tracker: https://github.com/mamoe/mirai/issues/new/choose
mirai-mirai-1  | 
mirai-mirai-1  | 常用资源整合
mirai-mirai-1  | `- https://mirai.mamoe.net/topic/653
mirai-mirai-1  |  
mirai-mirai-1  | MCL 已推出 2.1.0，更好的支持 Mirai 2.11 的插件系统，建议更新。
mirai-mirai-1  | 
mirai-mirai-1  |   05:11:04 [INFO] Verifying "net.mamoe:mirai-console" v2.14.0
mirai-mirai-1  |   05:11:06 [INFO] Verifying "net.mamoe:mirai-console-terminal" v2.14.0
mirai-mirai-1  |   05:11:07 [INFO] Verifying "net.mamoe:mirai-core-all" v2.14.0
mirai-mirai-1  |   05:11:07 [INFO] Verifying "org.itxtech:mcl-addon" v2.1.1
mirai-mirai-1  |   05:11:08 [INFO] Verifying "net.mamoe:mirai-api-http" v2.8.0
mirai-mirai-1  |   05:11:08 [INFO] Verifying "xyz.cssxsh.mirai:mirai-device-generator" v1.1.3
mirai-mirai-1  | 2023-02-19 05:11:11 I/main: Starting mirai-console...
mirai-mirai-1  | 2023-02-19 05:11:11 I/main: 
mirai-mirai-1  | 
mirai-mirai-1  | ==================================[ Mirai consosle 2.14.0 ]===================================
mirai-mirai-1  |  __       __ __                   __  ______                                      __
mirai-mirai-1  | |  \     /  \  \                 |  \/      \                                    |  \
mirai-mirai-1  | | ▓▓\   /  ▓▓\▓▓ ______   ______  \▓▓  ▓▓▓▓▓▓\ ______  _______   _______  ______ | ▓▓ ______
mirai-mirai-1  | | ▓▓▓\ /  ▓▓▓  \/      \ |      \|  \ ▓▓   \▓▓/      \|       \ /       \/      \| ▓▓/      \
mirai-mirai-1  | | ▓▓▓▓\  ▓▓▓▓ ▓▓  ▓▓▓▓▓▓\ \▓▓▓▓▓▓\ ▓▓ ▓▓     |  ▓▓▓▓▓▓\ ▓▓▓▓▓▓▓\  ▓▓▓▓▓▓▓  ▓▓▓▓▓▓\ ▓▓  ▓▓▓▓▓▓\
mirai-mirai-1  | | ▓▓\▓▓ ▓▓ ▓▓ ▓▓ ▓▓   \▓▓/      ▓▓ ▓▓ ▓▓   __| ▓▓  | ▓▓ ▓▓  | ▓▓\▓▓    \| ▓▓  | ▓▓ ▓▓ ▓▓    ▓▓
mirai-mirai-1  | | ▓▓ \▓▓▓| ▓▓ ▓▓ ▓▓     |  ▓▓▓▓▓▓▓ ▓▓ ▓▓__/  \ ▓▓__/ ▓▓ ▓▓  | ▓▓_\▓▓▓▓▓▓\ ▓▓__/ ▓▓ ▓▓ ▓▓▓▓▓▓▓▓
mirai-mirai-1  | | ▓▓  \▓ | ▓▓ ▓▓ ▓▓      \▓▓    ▓▓ ▓▓\▓▓    ▓▓\▓▓    ▓▓ ▓▓  | ▓▓       ▓▓\▓▓    ▓▓ ▓▓\▓▓     \
mirai-mirai-1  |  \▓▓      \▓▓\▓▓\▓▓       \▓▓▓▓▓▓▓\▓▓ \▓▓▓▓▓▓  \▓▓▓▓▓▓ \▓▓   \▓▓\▓▓▓▓▓▓▓  \▓▓▓▓▓▓ \▓▓ \▓▓▓▓▓▓▓
mirai-mirai-1  | 
mirai-mirai-1  | 
mirai-mirai-1  | 2023-02-19 05:11:11 I/main: Backend: version 2.14.0, built on 2023-02-06 06:25:21.
mirai-mirai-1  | 2023-02-19 05:11:11 I/main: Frontend Terminal: version 2.14.0, provided by Mamoe Technologies
mirai-mirai-1  | 2023-02-19 05:11:11 I/main: Welcome to visit https://mirai.mamoe.net/
mirai-mirai-1  | 2023-02-19 05:11:18 I/plugin: Successfully loaded plugin mirai-api-http v2.8.0
mirai-mirai-1  | 2023-02-19 05:11:18 I/plugin: Successfully loaded plugin mirai-device-generator v1.1.3
mirai-mirai-1  | 2023-02-19 05:11:18 I/plugin: Successfully loaded plugin MCL Addon v2.1.1
mirai-mirai-1  | 2023-02-19 05:11:18 I/main: Prepared built-in commands: autoLogin, help, login, logout, permission, status, stop
mirai-mirai-1  | 2023-02-19 05:11:19 I/Mirai HTTP API: ********************************************************
mirai-mirai-1  | 2023-02-19 05:11:19 I/MahKtorAdapter[http,ws]: Autoreload is disabled because the development mode is off.
mirai-mirai-1  | 2023-02-19 05:11:20 I/MahKtorAdapter[http,ws]: Application started in 0.697 seconds.
mirai-mirai-1  | 2023-02-19 05:11:20 I/MahKtorAdapter[http,ws]: Responding at http://localhost:8080
mirai-mirai-1  | 2023-02-19 05:11:20 I/http adapter: >>> [http adapter] is listening at http://localhost:8080
mirai-mirai-1  | 2023-02-19 05:11:20 I/ws adapter: >>> [ws adapter] is listening at ws://localhost:8080
mirai-mirai-1  | 2023-02-19 05:11:20 I/Mirai HTTP API: Http api server is running with verifyKey: 
mirai-mirai-1  | 2023-02-19 05:11:20 I/Mirai HTTP API: adaptors: [http,ws]
mirai-mirai-1  | 2023-02-19 05:11:20 I/Mirai HTTP API: ********************************************************
mirai-mirai-1  | 2023-02-19 05:11:20 I/MCL Addon: iTXTech MCL Version: 2.1.2-61c8bd8
mirai-mirai-1  | 2023-02-19 05:11:20 W/MCL Addon: iTXTech Soyuz 未安装，Soyuz MCL Handler 特性已禁用
mirai-mirai-1  | 2023-02-19 05:11:20 I/main: 3 plugin(s) enabled.
mirai-mirai-1  | 2023-02-19 05:11:20 I/main: Auto-login , protocol: ANDROID_PAD, heartbeatStrategy: STAT_HB
mirai-mirai-1  | 2023-02-19 05:11:22 I/Bot.930815393: Loaded account secrets from local cache.
mirai-mirai-1  | 2023-02-19 05:11:23 I/Bot.930815393: Saved account secrets to local cache for fast login.
mirai-mirai-1  | 2023-02-19 05:11:23 I/Bot.930815393: Login successful.
mirai-mirai-1  | 2023-02-19 05:11:28 V/Bot.930815393: Event: BotOnlineEvent(bot=Bot())
mirai-mirai-1  | 2023-02-19 05:11:28 I/Bot.930815393: Bot login successful.
mirai-mirai-1  | 2023-02-19 05:11:28 I/main: mirai-console started successfully.
mirai-mirai-1  | > 2023-02-19 05:11:28 W/console: Closing input service...

```
**chatgpt-mirai-qq-bot](https://github.com/lss233/chatgpt-mirai-qq-bot log**
```
2023-02-19 05:16:57.643 | WARNING  | graia.amnesia.builtins.aiohttp:connection_manage:229 - ClientOSError(104, 'Connection reset by peer')

2023-02-19 05:16:57.644 | WARNING  | graia.ariadne.connection.ws:_:75 - Websocket reconnecting in 5s...

2023-02-19 05:17:02.644 | WARNING  | graia.ariadne.connection.ws:_:77 - Websocket reconnecting...

2023-02-19 05:17:02.648 | WARNING  | graia.amnesia.builtins.aiohttp:connection_manage:229 - ClientOSError(104, 'Connection reset by peer')

2023-02-19 05:17:02.648 | WARNING  | graia.ariadne.connection.ws:_:75 - Websocket reconnecting in 5s...

2023-02-19 05:17:07.649 | WARNING  | graia.ariadne.connection.ws:_:77 - Websocket reconnecting...

2023-02-19 05:17:07.651 | WARNING  | graia.amnesia.builtins.aiohttp:connection_manage:229 - ClientOSError(104, 'Connection reset by peer')

```

**Comment by lss233** [comment]
先看 #142 
建议使用 Linux 一键脚本部署。

**Comment by 814850963** [comment]
@lss233 
你好，一键部署成功了，但是自己部署还是处于失败的状态(对于已经有mirai的用户来说)。建议再现一下这个问题然后解决比较好。

**Comment by lss233** [comment]
已经有mirai的用户，需要把 config.cfg 中 ws_url 和 http_url 的地址修改宿主机里的地址。  

或者你修改 docker-compose.yaml，将容器的网络设置为 host 模式：
```yaml
version: '3.4'
services:
  # 已有 mirai 不需要这一段
  # mirai:
  #   image: lss233/mirai-http:latest
  #   restart: always
  #   environment:
  #     LANG: 'C.UTF-8'
  #   volumes:
  #     - ./mirai/bots:/app/bots
  #     - ./mirai/config:/app/config
  #     - ./mirai/data:/app/data
  #     # - ./mirai/config.json:/app/config.json # 如果你要修改 mcl 的设置，就解除这个注释
  chatgpt:
    image: lss233/chatgpt-mirai-qq-bot:browser-version
    restart: always
    environment:
      LANG: 'C.UTF-8'
      XPRA_PASSWORD: 'xxxxx' # XPRA 密码，建议修改！！！！
    network_mode: 'host'
    volumes:
      - ./config.cfg:/app/config.cfg
      # - ./fonts:/app/fonts # 如果你想自定义字体，就解除注释
      # - ./presets:/app/presets # 如果你想自定义预设，就解除注释
  watchtower: # [可选] 自动更新
    image: containrrr/watchtower
    volumes: # 如果启动失败，请修改下面这条：
      - /var/run/docker.sock:/var/run/docker.sock
```
然后执行 docker-compose up -d 更新即可。
