### ISSUE TITLE
启动时报错

### ISSUE THREAD

**Issue by wuhuqifeiQWER** [lss233/chatgpt-mirai-qq-bot#165]
![image](https://user-images.githubusercontent.com/106081176/219937792-44c331eb-b36a-4011-a460-8546586d857c.png)
如图所示，py3.9我已经安装了，第一行有显示，但是启动bot.py的时候貌似还是调用的3.1，实在不会整了，望大佬解答！

**Comment by lss233** [comment]
你这 Python 环境太多了，导致混乱了吧。  
我觉得应该是因为 `python` 和 `python3` 启动的不是同一个 Python 导致的。   


建议用 docker 一键部署。

**Comment by wuhuqifeiQWER** [comment]
孩子没用过dockerQAQ，有没有什么其他的办法？先把所有py都卸掉再只装一个3.9可行吗？

**Comment by lss233** [comment]
上面说错了，用那个 Linux 一键脚本部署就可以了，帮你配好 docker 的，全程无痛。   

> 把所有py都卸掉再只装一个3.9可行吗？

这样也是可以的。

**Comment by wuhuqifeiQWER** [comment]
那个脚本我用不了，我是微软账户登录的chatgpt，没有密码。脚本的配置文件能手动改吗

**Comment by lss233** [comment]
> 那个脚本我用不了，我是微软账户登录的chatgpt，没有密码。脚本的配置文件能手动改吗

可以的，就在 `./chatpgt-qq/config.cfg` 里面。

**Comment by wuhuqifeiQWER** [comment]
![image](https://user-images.githubusercontent.com/106081176/219939419-b76c2899-7adc-4e22-a7bf-ea880021ba5c.png)
啊...寄

**Comment by lss233** [comment]
看来还是痛了一下。这是因为你不是 root 用户，默认没有 docker 的使用权。  
可以这样：
https://stackoverflow.com/questions/48568172/docker-sock-permission-denied  

然后 rm -rf chatgpt-qq
再重新执行脚本。

**Comment by wuhuqifeiQWER** [comment]
![image](https://user-images.githubusercontent.com/106081176/219939722-c7154ae6-6662-429f-a6b0-1efa92304ce2.png)
这是....系统架构问题嘛（

**Comment by lss233** [comment]
是的，请看 #81

**Comment by wuhuqifeiQWER** [comment]
![image](https://user-images.githubusercontent.com/106081176/219940740-de1b05d6-08a3-4f67-98f7-757be953d5f6.png)
然鹅貌似没用

**Comment by wuhuqifeiQWER** [comment]
而且卸掉py全删掉重装一般也没用

**Comment by lss233** [comment]
把第一个命令换成
```
docker pull --platform amd64 lss233/chatgpt-mirai-qq-bot:browser-version
```
试试，原来可能写错了

**Comment by wuhuqifeiQWER** [comment]
docker这怎么安装mirai的插件啊，直接docker-compose run --rm mirai安装完插件之后，docker-compose restartmirai没有任何变化，安了一个chat-command，发消息给机器人它不回复

**Comment by lss233** [comment]
```
docker-compose run --rm mirai
```
是不能装插件的。。

装插件的话你得去改 docker-compose.yaml 把 plugins 文件夹挂载出来，然后往里面放插件。  


发消息不回复的话查日志然后看别的 issue 是怎么处理的就行。

**Comment by wuhuqifeiQWER** [comment]
![image](https://user-images.githubusercontent.com/106081176/219942821-35a5dbd5-c49a-4850-b3db-b12a551058c6.png)
直接rnji扔进yaml就OK是吗

**Comment by lss233** [comment]
```yaml
version: '3.4'
services:
  mirai:
    image: lss233/mirai-http:latest
    restart: always
    environment:
      LANG: 'C.UTF-8'
    volumes:
      - ./mirai/bots:/app/bots
      - ./mirai/config:/app/config
      - ./mirai/data:/app/data
      - ./mirai/plugins:/app/plugins
  ```
docker-compose up -d

**Comment by lss233** [comment]
```yaml
version: '3.4'
services:
  mirai:
    image: lss233/mirai-http:latest
    restart: always
    environment:
      LANG: 'C.UTF-8'
    volumes:
      - ./mirai/bots:/app/bots
      - ./mirai/config:/app/config
      - ./mirai/data:/app/data
      - ./mirai/plugins:/app/plugins
  ```
docker-compose up -d
