### ISSUE TITLE
[BUG] 请问如何通过反向ws 连接至Mirai_onebot？

### ISSUE THREAD

**Issue by timeance** [lss233/chatgpt-mirai-qq-bot#340]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
按照配置文件设置后，无法通过onebot连接到Mirai

**运行环境:**  
- 操作系统：winser 2019
- 项目版本：2.2.3
- mirai：2.14.0
- onebot：kotlin-0.3.4

**复现步骤**  
描述你是如何触发这个 BUG 的
chatgpt的配置：
```
# 如果你想使用 go-cqhttp，则这么写：
# [onebot]
qq=123456
manager_qq = 123456
# 此处的  reverse_ws_host 和 reverse_ws_port 对应
# go-cqhttp 中的 反向WS Universal 地址，如：ws://localhost:6555/ws
reverse_ws_host = "127.0.0.1"
reverse_ws_port = 8556
```

onebot的配置：
```
    ws_reverse: 
      - enable: true
        postMessageFormat: string
        reverseHost: 127.0.0.1
        reversePort: 8556
        accessToken: ''
        reversePath: '/ws'
        reverseApiPath: '/api'
        reverseEventPath: '/event'
        useUniversal: true
        useTLS: false
        reconnectInterval: 3000
```
**预期行为**  
能够正常使用

**截图**  
![QQ截图20230313114506.png](https://pic.peo.pw/a/2023/03/13/640e9c940d631.png)

**其他内容**  
此处填写其他内容，没有可跳过
