### ISSUE TITLE
建议立刻升级到 Ariadne 到 0.9.10 或 0.10.2

### ISSUE THREAD

**Issue by ProgramRipper** [lss233/chatgpt-mirai-qq-bot#58]
您好，我是 GraiaProject 成员、Ariadne 贡献者 @ProgramRipper。

由于 [Ariadne 0.9.0](https://github.com/GraiaProject/Ariadne/releases/tag/v0.9.0) 中的修改 `对好友，群，群成员和版本等信息使用缓存 (@ProgramRipper)` 引入的 bug，Ariadne 会缓存全部好友、群、群成员、消息和版本信息，并且**不会过期**，导致严重的内存泄露。

这一问题已在 https://github.com/GraiaProject/Ariadne/pull/206 和 https://github.com/GraiaProject/Ariadne/commit/3ad9a6109cc704e139315c637483f869f6beb13f (0.9 backport) 中修复，并随后发布了修复版本 [Ariadne 0.10.2](https://github.com/GraiaProject/Ariadne/releases/tag/v0.10.2) 和 [Ariadne 0.9.10](https://github.com/GraiaProject/Ariadne/releases/tag/v0.9.10)。

这一问题波及使用了 Ariadne 0.9.0~0.9.8, 0.10.0 的**所有**应用（只要接收消息就有内存泄露风险）。很遗憾，此仓库正受到此问题影响。您可以通过**升级 Ariadne** 来修复这一问题：

```shell
pip install --upgrade graia-ariadne
poetry update graia-ariadne
pdm update graia-ariadne
```

```toml
# pyproject.toml
## poetry
[tool.poetry.dependencies]
graia-ariadne = "^0.10.2"
### or backport...
graia-ariadne = "^0.9.10" 

## pdm
dependencies = [
    "graia-ariadne>=0.10.2",
    # ...
]
### or backport...
dependencies = [
    "graia-ariadne>=0.9.10",
    # ...
]
```

```txt
# requirements.txt
graia-ariadne==0.10.2
### or backport...
graia-ariadne==0.9.10
```

如果您的仓库中有 poetry.lock 或 pdm.lock 文件，也请不要忘记通过 `poetry lock` 或 `pdm lock` 更新它们。

在此，我对此问题已造成的损失，以及因为此问题而耽误您的宝贵时间和精力而感到抱歉。如果您有更多问题，可以在此议题下回复，我将尽我所能提供解答、协助。
