### ISSUE TITLE
404

### ISSUE THREAD

**Issue by JYlYK** [lss233/chatgpt-mirai-qq-bot#861]
**提交 issue 前，请先确认：**
- [√] 我已看过 **FAQ**，此问题不在列表中
- [ √] 我已看过其他 issue，他们不能解决我的问题 
- [？] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
对bot切换chatgpt-api模式后，与bot对话一直出现
......原因：404  {"timestamp":"（发送对话的时间）","status":404,"error":"Not Found","message":"","path":"/chat/completions"}

**运行环境:**  
- 操作系统：云服务器Linux端
- Docker： ？
- 项目版本：最新

**复现步骤**  
向bot发送 指令 “切换AI chatgpt-api” 后，bot提示切换成功
之后再次与bot进行正常对话时就会出现原因为404的错误

注：chatgpt-web端使用正常

**Comment by lss233** [comment]
这可能是因为你配置了错误的 api_endpoint。

**Comment by JYlYK** [comment]
> 这可能是因为你配置了错误的 api_endpoint。

![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/133961619/f438dd71-26af-4ced-b1d9-29a2697ca458)
这是我的 api_endpoint 配置，请问是哪里出现了问题，我应该如何解决？

**Comment by lss233** [comment]
不是很懂你这个 endpoint 是哪里来的，参考配置：
```toml
[openai]
# API 接入点，欢迎在交流群中分享你的接入点
api_endpoint = "https://chatgpt-proxy.lss233.com/v1"
```
