### ISSUE TITLE
[Feature] 能否改一下前缀判断逻辑

### ISSUE THREAD

**Issue by Nothingness-Void** [lss233/chatgpt-mirai-qq-bot#867]
如题
 
本人想实现的效果是在群里@机器人即可触发

而好友需要加前缀对话才能触发

但是目前看来不设置全局前缀无法设置好友前缀

**Comment by lss233** [comment]
```toml
[trigger]

# 全局聊天前缀设置为空
prefix = []

# 私聊聊天前缀需要加前缀才能触发
prefix_friend = [ "gpt"]

# 群聊聊天设置为无需前缀
prefix_group = [ ""]

# 在群里 at 即可触发
require_mention = "at"
```
