### ISSUE TITLE
[文档] endpoint搭建方法参考

### ISSUE THREAD

**Issue by INSide-734** [lss233/chatgpt-mirai-qq-bot#978]
# browserless_endpoint搭建方式
## 注意：
如果搭建出错了请不要在此issue或者此项目下提新的issue，请到相应的项目下提issue
### 要求: 
可以正常访问 `chat.openai.com` 且在[被支持的国家或地区](https://platform.openai.com/docs/supported-countries)内

### 使用的项目
[go-chatgpt-api](https://github.com/linweiyuan/go-chatgpt-api)
[ChatGPT-Proxy-V4](https://github.com/acheong08/ChatGPT-Proxy-V4)

# go-chatgpt-api
##  配置文件
根据你的网络环境不同，可以展开查看对应配置

<details>

<summary>直接利用现成的服务</summary>

服务器不定时维护，不保证高可用，利用这些服务导致的账号安全问题，与本项目无关

- https://go-chatgpt-api.linweiyuan.com
- https://api.tms.im

</details>

<details>

<summary>家庭网络</summary>

```yaml
  go-chatgpt-api:
    container_name: go-chatgpt-api
    image: linweiyuan/go-chatgpt-api
    ports:
      - 8080:8080
    environment:
      - TZ=Asia/Shanghai
      - GO_CHATGPT_API_PROXY=
      - GO_CHATGPT_API_PANDORA=
      - GO_CHATGPT_API_ARKOSE_TOKEN_URL=
      - GO_CHATGPT_API_ARKOSE_PUID=
    restart: unless-stopped
```

</details>

<details>

<summary>服务器在直连或者通过网络代理的情况下可以正常访问 ChatGPT</summary>

```yaml
  go-chatgpt-api:
    container_name: go-chatgpt-api
    image: linweiyuan/go-chatgpt-api
    ports:
      - 8080:8080
    environment:
      - TZ=Asia/Shanghai
      - GO_CHATGPT_API_PROXY=
      - GO_CHATGPT_API_PANDORA=
      - GO_CHATGPT_API_ARKOSE_TOKEN_URL=
      - GO_CHATGPT_API_ARKOSE_PUID=
    restart: unless-stopped
```

</details>

<details>

<summary>服务器访问 ChatGPT 提示 "Sorry, you have been blocked"</summary>

如何验证：`curl https://chat.openai.com | grep '<p>' | awk '{$1=$1;print}'`

```yaml
  go-chatgpt-api:
    container_name: go-chatgpt-api
    image: linweiyuan/go-chatgpt-api
    ports:
      - 8080:8080
    environment:
      - TZ=Asia/Shanghai
      - GO_CHATGPT_API_PROXY=socks5://chatgpt-proxy-server-warp:65535
      - GO_CHATGPT_API_PANDORA=
      - GO_CHATGPT_API_ARKOSE_TOKEN_URL=
      - GO_CHATGPT_API_ARKOSE_PUID=
    depends_on:
      - chatgpt-proxy-server-warp
    restart: unless-stopped

  chatgpt-proxy-server-warp:
    container_name: chatgpt-proxy-server-warp
    image: linweiyuan/chatgpt-proxy-server-warp
    environment:
      - LOG_LEVEL=OFF
    restart: unless-stopped
```

</details>

---

## 设置代理
如需设置代理，可以设置环境变量 `GO_CHATGPT_API_PROXY`，比如 `GO_CHATGPT_API_PROXY=http://127.0.0.1:20171`
或者 `GO_CHATGPT_API_PROXY=socks5://127.0.0.1:20170`，注释掉或者留空则不启用

如果代理需账号密码验证，则 `http://username:password@ip:port` 或者 `socks5://username:password@ip:port`

如需配合 `warp` 使用：`GO_CHATGPT_API_PROXY=socks5://chatgpt-proxy-server-warp:65535`，因为需要设置 `warp`
的场景已经默认可以直接访问 `ChatGPT` 官网，因此共用一个变量不冲突（国内 `VPS` 不在讨论范围内，请自行配置网络环境，`warp`
服务在魔法环境下才能正常工作）

家庭网络无需跑 `warp` 服务，跑了也没用，会报错，仅在服务器需要

`GPT-4` 相关模型目前需要验证 `arkose_token`，如果配置 `GO_CHATGPT_API_ARKOSE_TOKEN_URL` 则使用在线服务获取 `arkose_token`
，不设置或者留空则由程序内部自己生成（推荐优先使用这种）

`GO_CHATGPT_API_ARKOSE_TOKEN_URL` 可选值：

- https://arkose-token.linweiyuan.com
- https://arkose-token.tms.im
- http://arkosetoken.52swap.cn
- https://a-token.xiu.ee
- https://tttoken.azurewebsites.net
- https://arkosetoken.tsmai.top

如果用以上方法还是 `403` 并且你的 `Plus`
没有过期，则有一种可能就是你的账号被风控了，可以尝试用这个账号打开官网，看下会不会弹验证码，然后手动处理下，接着再回来看 `go-chatgpt-api`
还会不会 `403`

---

目前 `warp` 容器检测到流量超过 1G 会自动重启，如果你知道什么是 `teams-enroll-token`
（不知道就跳过），可以通过环境变量 `TEAMS_ENROLL_TOKEN`
设置它的值，然后利用这条命令来检查是否生效

`docker-compose exec chatgpt-proxy-server-warp warp-cli --accept-tos account | awk 'NR==1'`

```
Account type: Free （没有生效）

Account type: Team （设置正常）
```

### 填写接入点地址

接下来就可以在[chatgpt-mirai-qq-bot](https://github.com/lss233/chatgpt-mirai-qq-bot)的config.cfg中填写`browserless_endpoint`了，示例:
```
[openai]
# 网页版 ChatGPT 接入点，欢迎在交流群中分享你的接入点
browserless_endpoint = "http(s)://127.0.0.1:8080/chat/"
```

# ChatGPT-Proxy-V4
由于作者没有提供`docker`镜像，所以需要自己手动构建镜像运行或者从[Release](https://github.com/acheong08/ChatGPT-Proxy-V4/releases/)下载可执行文件

注意，有一个基于IP的速率限制。需要设置一个PUID环境变量来解决这个问题 `export PUID="user-... "` 这需要ChatGPT Plus帐户

## 以下是`docker`运行方式
```
# clone 至本地
git clone https://github.com/acheong08/ChatGPT-Proxy-V4.git
# cd 至目录
cd ChatGPT-Proxy-V4
# docker构建镜像
docker build -t chatgpt-proxy-v4 .
```

`docker-compose.yml`示例
```yaml
version: '3.3'
services:
    chatgpt-proxy:
        image: chatgpt-proxy-v4
        container_name: chatgpt-proxy-v4
        ports:
            - '8080:8080'
        env_file:
        - .env
```
接下来就可以在[chatgpt-mirai-qq-bot](https://github.com/lss233/chatgpt-mirai-qq-bot)的config.cfg中填写`browserless_endpoint`了，示例:
```
[openai]
# 网页版 ChatGPT 接入点，欢迎在交流群中分享你的接入点
browserless_endpoint = "http(s)://127.0.0.1:8080/api/"
```
